model = "gpt-5.2-codex"
approval_policy = "never"
sandbox_mode = "danger-full-access"
model_reasoning_effort = "medium"
suppress_unstable_features_warning = true

[sandbox_workspace_write]
network_access = true

[features]
unified_exec = true
shell_snapshot = true
web_search_request = true
collab = true
collaboration_modes = true
steer = true

[notice]
hide_rate_limit_model_nudge = true
