model = "gpt-5.2-codex"
approval_policy = "never"
sandbox_mode = "danger-full-access"
model_reasoning_effort = "high"

[sandbox_workspace_write]
network_access = true

[features]
unified_exec = true
shell_snapshot = true
web_search_request = true
collab = true
